#!/bin/bash
#2015/06/27: Guillaume REMBERT
#EuryBOX exec commands script

START_TIME=$(date +%s)

#########################
# SCRIPT INITIALISATION #
#########################

#Get configuration variables and functions
SCRIPT_COMMAND=$(readlink -f "$0")
SCRIPT_ARGUMENTS="$@"
SCRIPT_PATH=$(dirname "$SCRIPT_COMMAND")

#Should not be changed except if you changed sw folder layout
SCRIPT_CONF_PATH=$SCRIPT_PATH/../../../../../cfg/sw/eurybox.conf
SCRIPT_FUNC_PATH=$SCRIPT_PATH/../../../eurybox.functions

#Check and load ressources
if [[ -f $SCRIPT_CONF_PATH && -f $SCRIPT_FUNC_PATH ]]
then
  source $SCRIPT_CONF_PATH
  source $SCRIPT_FUNC_PATH
  eurybox_message_display debug STATUS "Configuration and function scripts successfully sourced"
else
  echo "[EURYBOX][ERROR][RESSOURCES] Configuration file $SCRIPT_CONF_PATH or functions file $SCRIPT_FUNC_PATH not found. Stopping execution"
  exit 1
fi
eurybox_message_display message STATUS "Checking configuration"
eurybox_check_configuration BACKUP

#Check input parameters
eurybox_message_display message STATUS "Checking parameters"
eurybox_check_arguments $SCRIPT_ARGUMENTS

#Check environment
eurybox_message_display message STATUS "Checking environment"
eurybox_check_environment BACKUP

eurybox_message_display message STATUS "$EURYBOX_CORPORATE exec commands script started"


#Start all VMs
euryboxctrl_start_services

#Execution commands on virtual machines / services
euryboxctrl_exec_command_services

#Finished
END_TIME=$(date +%s)
DIFF_TIME=$(( $END_TIME - $START_TIME ))
eurybox_message_display message STATUS "Command exec finished"
eurybox_message_display message TIMING "Command exec took $DIFF_TIME seconds"
