#!/bin/bash
#EuryBOX restoration script

START_TIME=$(date +%s)

#########################
# SCRIPT INITIALISATION #
#########################

#Get configuration variables and functions
SCRIPT_COMMAND=$(readlink -f "$0")
SCRIPT_ARGUMENTS="$@"
SCRIPT_PATH=$(dirname "$SCRIPT_COMMAND")

#Should not be changed except if sw folder layout is changed
SCRIPT_CONF_PATH=$SCRIPT_PATH/../../../../../cfg/sw/eurybox.conf
SCRIPT_FUNC_PATH=$SCRIPT_PATH/../../../eurybox.functions

#Check and load ressources
if [[ -f $SCRIPT_CONF_PATH && -f $SCRIPT_FUNC_PATH ]]
then
  source $SCRIPT_CONF_PATH
  source $SCRIPT_FUNC_PATH
  eurybox_display_message debug STATUS "Configuration and function scripts successfully sourced"
else
  echo "[EURYBOX][ERROR][RESSOURCES] Configuration file $SCRIPT_CONF_PATH or functions file $SCRIPT_FUNC_PATH not found. Stopping execution"
  exit 1
fi
eurybox_display_message message STATUS "Checking configuration"
eurybox_check_configuration RESTORE

#Check input parameters
eurybox_display_message message STATUS "Checking parameters"
eurybox_check_arguments $SCRIPT_ARGUMENTS

#Check environment
eurybox_display_message message STATUS "Checking environment"
eurybox_check_environment RESTORE

eurybox_display_message message STATUS "$EURYBOX_CORPORATE restoration script started"

######################
# ARCHIVES DISCOVERY #
######################

#Discover available archives
euryboxctrl_discover_available_archives

#Select archive to be restored
euryboxctrl_select_restore_target

#Prepare environment for restoration
euryboxctrl_prepare_restore

case $EURYBOX_RESTORE_TYPE in
  cloned_vm )
########################
# CLONE VM RESTORATION #
########################
    eurybox_display_message warning STATUS "CLONE VM RESTORE NOT AVAILABLE YET"
  ;;
  cloned_full )
#####################################
# CLONE VM + HYPERVISOR RESTORATION #
#####################################
    eurybox_display_message warning STATUS "CLONE VM + HV RESTORE NOT AVAILABLE YET"
  ;;
  full )
########################################
# FULL SYSTEM RESTORATION + VM REFRESH #
########################################
    eurybox_display_message warning STATUS "FULL RESTORE NOT AVAILABLE YET"
  ;;
  * )
    eurybox_display_message warning STATUS "Unknown restoration type: $EURYBOX_RESTORE_TYPE"
  ;;
esac

euryboxctrl_terminate_restore


#Finished
END_TIME=$(date +%s)
DIFF_TIME=$(( $END_TIME - $START_TIME ))
eurybox_display_message message STATUS "Restoration finished"
eurybox_display_message message TIMING "Restoration took $DIFF_TIME seconds"
